config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "pages#index"
  
  resources :bank_accounts
  
  resources :clients do
    resources :bank_accounts, controller: "clients/bank_accounts", except: [:index, :show, :destroy]
  end

  namespace :api do
    namespace :v1 do
      post "bank_accounts/new_transaction", to: "bank_accounts#new_transaction"
    end
  end
end

app/models/account_transaction.rb
class AccountTransaction < ApplicationRecord
  belongs_to :bank_account

  TRANSACTION_TYPES = ["withdraw", "deposit"]
  validates :bank_account, presence: true
  validates :amount, presence: true, numericality: true
  validates :transaction_type, presence: true, inclusion: { in: TRANSACTION_TYPES }
  validates :transaction_number, presence: true, uniqueness: true

  before_validation :load_defaults

  def load_defaults
    if self.new_record?
      self.transaction_number = SecureRandom.uuid
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
  belongs_to :client

  validates :client, presence: true
  validates :account_number, presence: true, uniqueness: true
  validates :balance, presence: true, numericality: true

  before_validation :load_defaults
  has_many :account_transactions

  def load_defaults
    if self.new_record?
      self.balance = 0.00
    end
  end

  def to_s
    account_number
  end
end

app/models/client.rb
class Client < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :client_number, presence: true, uniqueness: true

  has_many :bank_accounts

  before_save :format_name

  def format_name
    self.first_name = self.first_name.upcase
    self.last_name  = self.last_name.upcase
  end

  def num_accounts
    self.bank_accounts.count
  end
  
  def to_s
    "#{last_name}, #{first_name}"
  end
end

app/controllers/api/v1/bank_accounts_controller.rb
module Api
  module V1
    class BankAccountsController < ApplicationController
      
      def new_transaction
        amount           = params[:amount]
        transaction_type = params[:transaction_type]
        bank_account_id  = params[:bank_account_id]

        errors = ::BankAccounts::ValidateNewTransaction.new(
                  amount: amount,
                  transaction_type: transaction_type,
                  bank_account_id: bank_account_id
                ).execute!

        if errors.size > 0
          render json: { errors: errors }, status: 402
        else
          bank_account = ::BankAccounts::PerformTransaction.new(
                          amount: amount,
                          transaction_type: transaction_type,
                          bank_account_id: bank_account_id
                        ).execute!

          render json: { balance: bank_account.balance }
        end
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery with: :exception

end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController
  def index
    @bank_accounts = BankAccount.all
  end

  def new
    @bank_account = BankAccount.new
  end

  def create
    @bank_account = BankAccount.new(bank_account_params)
    
    if @bank_account.save
      redirect_to bank_account_path(@bank_account.id)
    else
      render "new"
    end
  end

  def edit
    @bank_account = BankAccount.find(params[:id])
  end

  def update
    @bank_account = BankAccount.find(params[:id])

    if @bank_account.update(bank_account_params)
      redirect_to bank_account_path(@bank_account.id)
    else
      render "edit"
    end
  end

  def destroy
    bank_account = BankAccount.find(params[:id])
    client       = bank_account.client

    if bank_account.balance > 0
      redirect_to bank_account_path(bank_account.id)
    else
      bank_account.destroy!
      redirect_to client_path(client)
    end
    
  end

  def show
    @bank_account = BankAccount.find(params[:id])
  end

  private

  def bank_account_params
    params.require(:bank_account).permit(:account_number, :client_id)  
  end
end

app/controllers/clients/bank_accounts_controller.rb
module Clients
  class BankAccountsController < ApplicationController
    before_action :load_parent_object
    before_action :load_object, only: [:edit, :update]

    def new
      @bank_account = BankAccount.new
    end

    def create
      @bank_account = BankAccount.new(bank_account_params)
      @bank_account.client = @client
      if @bank_account.save
        redirect_to bank_account_path(@bank_account.id)
      else
        render "new"
      end
    end

    def edit
      @bank_account = BankAccount.find(params[:id])
    end

    def update
      @bank_account.client = @client
      if @bank_account.update(bank_account_params)
        redirect_to bank_account_path(@bank_account.id)
      else
        render "edit"
      end
    end

    private

    def load_object
      @bank_account = BankAccount.find(params[:id])
    end

    def load_parent_object
      @client       = Client.find(params[:client_id])
    end

    def bank_account_params
      params.require(:bank_account).permit(:account_number)
    end
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @clients = Client.all
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    
    if @client.save
      redirect_to client_path(@client.id)
    else
      render "new"
    end
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])

    if @client.update(client_params)
      redirect_to client_path(@client.id)
    else
      render "edit"
    end
  end

  def destroy
    @client = Client.find(params[:id])

    if @client.balance > 0
      redirect_to client_path(@client.id)
    else 
      @client.destroy!
      redirect_to clients_path
    end
    
  end

  def show
    @client = Client.find(params[:id])
  end

  private

  def client_params
    params.require(:client).permit(:client_number, :first_name, :last_name)  
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
def index
  
end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  def number_of_accounts
    BankAccount.count
  end
  def number_of_clients
    Client.count
  end
end

app/views/bank_accounts/_form.html.haml
= simple_form_for bank_account do |f|
  = f.input :account_number, input_html: { class: "form-control"}
  =f.association :client, input_html: {class: "form-control"}

  %hr
  =button_tag type: :submit, class: "btn btn-primay" do
    Save Bank Account
  =link_to root_path, class: "btn btn-default" do
    Cancel

app/views/bank_accounts/_modal_transaction.html.haml
#modal-transaction.modal.fade.modal-fade
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{type:'button', data:{dismiss:'modal'}}
          %span{aria:{hidden:'true'}}
            %i.fa.fa-close
          %span.sr-only Close
        %h4.modal-title
          New Transaction
      .modal-body
        .row
          .col-md-12
            .notification
        .row
          .col-md-6
            %label
              Amount
            = text_field_tag :amount, 0.00, id: "input-amount", class: "form-control"
          .col-md-6
            %label
              Transaction Type
            = select_tag :transaction_type, options_for_select(AccountTransaction::TRANSACTION_TYPES), id: "select-trans-type", class: "form-control"
      .modal-footer
        %button.btn.btn-default{type:'button', data:{dismiss:'modal'}} Close
        %button.btn.btn-primary{type:'button', id: "btn-save"} Save

app/views/bank_accounts/_transactions.html.haml
%table.table.table-bordered
  %thead
    %tr
      %th Date of transaction
      %th Amount
      %th Transaction type
  %tbody
    - bank_account.account_transactions.each do |t|
      %tr
        %td #{t.created_at}
        %td #{t.transaction_type}
        %td #{number_to_currency(t.amount, unit: "COP ")}
    %tr
      %th
      %th Balance
      %th #{number_to_currency(bank_account.balance, unit: "COP ")}

#parameters{ data: {bank_account_id: @bank_account.id } }

app/views/bank_accounts/edit.html.haml
%h1
  Edit Bank Account
  %small
    #{@bank_account.account_number}

=render partial: "form", locals: { bank_account: @bank_account }

app/views/bank_accounts/index.html.haml
//index bank account
%h1
  Bank Accounts

= link_to new_bank_account_path, class: "btn btn-primary" do 
  New Bank Account

%table.table.table-bordered
  %thead
    %tr
      %th Account Number
      %th Customer
      %th Balance
      %th Actions
  %tbody
    - @bank_accounts.each do |bank_account|
      %tr
        %td #{bank_account.account_number}
        %td 
          = link_to client_path(bank_account.client.id) do
            #{bank_account.client}
        %td #{number_to_currency(bank_account.balance, unit: "COP ")}
        %td
          = link_to bank_account_path(bank_account.id), class: "btn btn-primary" do
            Show

app/views/bank_accounts/new.html.haml
%h1
  New Bank Account

=render partial: "form", locals: { bank_account: @bank_account }

app/views/bank_accounts/show.html.haml
%h1 
  Account Number: #{@bank_account.account_number}
  %small
    #{@bank_account.client}

= button_tag :new_transaction, id: "btn-new-transaction", class: "btn btn-primary" do
  New Transaction

= link_to client_path(@bank_account.client.id), class: "btn btn-default" do
  Back to #{@bank_account.client}

= link_to bank_accounts_path, class: "btn btn-default" do
  Back to Bank Accounts

=render partial: "transactions", locals: {bank_account: @bank_account }

=link_to edit_bank_account_path(@bank_account.id), class: "btn btn-info" do
  Edit Bank Account

=link_to bank_account_path(@bank_account.id), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure?" } do
  Delete Bank Account

=render partial: "modal_transaction"


= javascript_include_tag "bank_accounts/show"
:javascript
  $(document).ready(function() {
    Show.init()
  });

    

app/views/clients/_bank_accounts.html.haml
%table.table.table-bordered
  %thead
    %tr
      %th Account Number
      %th Balance
      %th Actions
  %tbody
    - bank_accounts.each do |bank_account|
      %tr
        %td #{bank_account.account_number}
        %td #{number_to_currency(bank_account.balance, unit: "COP ")}
        %td
          = link_to bank_account_path(bank_account.id), class: "btn btn-info" do
            Show

app/views/clients/_form.html.haml
= simple_form_for client do |f|
  .row
    .col-md-12
      = f.input :client_number, input_html: {class: "form-control"}
  .row
    .col-md-4
      =f.input :first_name, input_html: {class: "form-control"}
    .col-md-4
      =f.input :last_name, input_html: {class: "form-control"}
    .col-md-4

 
  %hr
  =button_tag type: :submit, class: "btn btn-primay" do
    Save Client
  - if client.new_record?
    =link_to clients_path, class: "btn btn-default" do
      Cancel
  - else
    = link_to client_path(client.id), class: "btn btn-default" do
      Cancel

app/views/clients/_list.html.haml
%table.table.table-bordered
  %thead
    %tr
      %th Client Number
      %th Name
      %th # of Accounts
      %th Actions
  %tbody
    - clients.each do |c|
      %tr
        %td #{c.client_number}
        %td #{c}
        %td #{c.num_accounts}
        %td
          =link_to client_path(c.id), class: "btn btn-primary" do
            Show

app/views/clients/bank_accounts/_form.html.haml
= simple_form_for [client, bank_account] do |f|
  =f.input :account_number, input_html: {class: "form-control"}

  %hr
  =button_tag type: :submit, class: "btn btn-primay" do
    Save Bank Account
  =link_to client_path(client.id), class: "btn btn-default" do
    Cancel

app/views/clients/bank_accounts/edit.html.haml
%h1
  Edit Bank Account for #{@client}

= render partial: "form", locals: {client: @client, bank_account: @bank_account}

app/views/clients/bank_accounts/new.html.haml
%h1
  New Bank Account for #{@client}

= render partial: "form", locals: {client: @client, bank_account: @bank_account}

app/views/clients/edit.html.haml
%h1
  Edit Client #{@client}

=render partial: "form", locals: {client: @client}

app/views/clients/index.html.haml
%h1
  Clients List

= link_to new_client_path, class: "btn btn-primay" do
  New Client

= render partial: "list", locals: {clients: @clients}

app/views/clients/new.html.haml
%h1
  New Client

=render partial: "form", locals: {client: @client}

app/views/clients/show.html.haml
%h1
  Customer: #{@client} 
  %small
    #{@client.client_number}

=link_to edit_client_path(@client), class: "btn btn-info" do
  Edit Client

=link_to new_client_bank_account_path(@client.id), class: "btn btn-primary" do
  New Bank Account
= render partial: "bank_accounts", locals: { bank_accounts: @client.bank_accounts }

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bankpapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            <%= link_to "Bankpapp", root_path, class: "navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="">

              <%= link_to "Clients", clients_path, class: "navbar-brand" %> 
            </li>
            <li>
              <%= link_to "BankAccounts", bank_accounts_path, class: "navbar-brand" %>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
   
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.haml
%h1
  Welcome
- if @number_of_clients == 0
  =link_to clients_path, class: "btn btn-primay" do
    New Client

.row
  .col-md-6
    .panel.panel-success
      .panel-heading
        Number of accounts:
      .panel-body
        #{number_of_accounts}
    
  .col-md-6
    .panel.panel-success
      .panel-heading
        Number of clients:
      .panel-body
        #{number_of_clients}